---
- name: install apache web server
  package: 
    name: apache2
    state: present

- name: starting services
  service: 
     name: apache2
     state: started
     enabled: yes    

