---

- name: add php repository
  apt_repository:
     repo: 'ppa:ondrej/php' 
     state: present 
     update_cache: yes
- name: installing php
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - php7.2
    - php7.2-curl
    - php7.2-gd
    - php7.2-cli
    - php7.2-mysql
    - php7.2-xml
    - php7.2-mbstring
    - php7.2-fpm
    - php7.2-json
    - php7.2-intl
    - php7.2-zip

- name: starting services
  service: 
    name: php7.2-fpm   
    state: started
    enabled: yes


